"""empty message

Revision ID: 047e6dab112d
Revises: 555a385620d4
Create Date: 2024-05-09 08:52:39.921076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047e6dab112d'
down_revision = '555a385620d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('naves', schema=None) as batch_op:
        batch_op.alter_column('cost_in_credits',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('naves', schema=None) as batch_op:
        batch_op.alter_column('cost_in_credits',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
