"""empty message

Revision ID: 998defa93feb
Revises: 9df46b2823d1
Create Date: 2024-05-09 07:31:31.063882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998defa93feb'
down_revision = '9df46b2823d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mass', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=200), nullable=True))
        batch_op.drop_column('altura')
        batch_op.drop_column('color_piel')
        batch_op.drop_column('peso')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('color_piel', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('altura', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('mass')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
