"""empty message

Revision ID: 9df46b2823d1
Revises: fff24971e7ed
Create Date: 2024-05-09 07:22:14.658078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df46b2823d1'
down_revision = 'fff24971e7ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
