"""empty message

Revision ID: bb7119c91e4b
Revises: a865edca8995
Create Date: 2024-05-09 07:04:21.563331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7119c91e4b'
down_revision = 'a865edca8995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planeta_id', sa.Integer(), nullable=True),
    sa.Column('personaje_id', sa.Integer(), nullable=True),
    sa.Column('nave_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nave_id'], ['naves.id'], ),
    sa.ForeignKeyConstraint(['personaje_id'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['planeta_id'], ['planetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_nave_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('users_personaje_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('users_planeta_id_fkey', type_='foreignkey')
        batch_op.drop_column('nave_id')
        batch_op.drop_column('personaje_id')
        batch_op.drop_column('planeta_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planeta_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('personaje_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nave_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_planeta_id_fkey', 'planetas', ['planeta_id'], ['id'])
        batch_op.create_foreign_key('users_personaje_id_fkey', 'personajes', ['personaje_id'], ['id'])
        batch_op.create_foreign_key('users_nave_id_fkey', 'naves', ['nave_id'], ['id'])

    op.drop_table('favoritos')
    # ### end Alembic commands ###
