"""empty message

Revision ID: ccefecf269ab
Revises: bb7119c91e4b
Create Date: 2024-05-09 07:13:46.513601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccefecf269ab'
down_revision = 'bb7119c91e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('periodo_rotacion', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('poblacion', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.drop_column('poblacion')
        batch_op.drop_column('periodo_rotacion')

    # ### end Alembic commands ###
